### ISSUE TITLE
Error with 10.2.5

### ISSUE THREAD

**Issue by MetalHeadSeven** [Jaslm/ColorPickerPlus#13]
1x ColorPickerPlus/ColorPickerPlus.lua:325: attempt to index global 'ColorPickerWheel' (a nil value)
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:325: in function `CleanUpColorPickerFrame'
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:1109: in function `Initialize_UI'
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:1137: in function `?'
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:137: in function <ColorPickerPlus/ColorPickerPlus.lua:137>

Locals:
self = <table> {
 CreateClassPalette = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:613
 CreateCheckerboardBG = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:374
 CreateOpacityBar = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:920
 ShowHideAlpha = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:291
 CleanUpColorPickerFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:322
 Initialize_UI = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1108
 UpdateOldColor = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:222
 CreateHelpFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1051
 UpdateOpacityBarThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:260
 CreateTextBoxes = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:950
 UpdateHexText = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1264
 CreateColorGradient = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:731
 Hooked_OnShow = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:308
 UpdateAlphaText = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1288
 UpdateHSVfromColorPickerRGB = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:194
 PLAYER_LOGIN = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1135
 UpdateRGBTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1252
 UpdateChosenColor = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:216
 UpdateColorTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1234
 CreatePalette = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:555
 UpdateHueBarThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:267
 CreateColorSwatches = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:415
 SetRGBfromHSV = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:197
 CreatePaletteSwitcher = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1093
 UpdateHSVTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1240
 GetAlpha = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:201
 CreatePaletteFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1068
 ADDON_LOADED = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:226
 UpdateColorGraphics = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:274
 CreateCopyPasteArea = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:446
 UpdateGradientColorOverlay = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:211
 UpdateGradientThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:245
 HexTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1176
 RGBTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1141
 CreateHueBar = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:827
 AlphaTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1274
 HSVTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1200
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ColorPickerWheel' (a nil value)"
isClassic = false
isWrath = false
dialogHeight = 380

**Comment by Surarn** [comment]
Hey, i commented my fix on CurseForge, this is more meant for the author if he is busy and wants one solution to the errors.

> Hello, on todays patch they did some changes to various stuff, i overwrote my export code so i cant see the previous version for the ColorPickerFrame but managed to get it to work.
> 
> They renamed OpacitySliderFrame to OpacityFrameSlider, replacing all instances of this worked.
> 
> Seems like they changed the organization of the frame, earlier it was ColorPickerFrame:SetColorRGB but it is now ColorPickerFrame.Content.ColorPicker:SetColorRGB, replacing all instances of this worked.
> 
> In your function CleanUpColorPickerFrame you are hiding several frames, since their reorganization the names are changed so i simply commented out all of those except for OpacityFrameSlider, instead added 
> 
> ```
> local ColorPickerFrame = ColorPickerFrame
> ColorPickerFrame:HookScript("OnShow",
>  function ()
> 	ColorPickerFrame.Content.ColorPicker.Alpha:Hide();
> 	ColorPickerFrame.Content.ColorPicker.AlphaThumb:Hide();
> 	ColorPickerFrame.Content.AlphaBackground:Hide();
> 	ColorPickerFrame.Content.ColorPicker:Hide()
> 	ColorPickerFrame.Content.HexBox:Hide()
> 	ColorPickerFrame.Content.ColorSwatchOriginal:Hide()
> 	ColorPickerFrame.Content.ColorSwatchCurrent:Hide()
>  end
> )
> ```
> 
>  
> 
> It works, dont know if this is a bad way to solve it though, i couldnt do it like you did since blizz now seems to call Show each time the main window shows.
> 
>  
> 
> After calling SetColorRGB you seem to call ColorPickerFrame.func, since i dont have the previous version i dont know what function this is, i found ColorPickerFrame.swatchFunc which i guess is the renamed function. However in blizz documentation they comment that "SetColorRGB must be called last since it triggers swatchFunc", so simply commenting out all instances of ColorPickerFrame.func in your addon fixed that issue, i guess in the previous version SetColorRGB didnt call func.
> 
>  
> 
> And with those changes the addon seems to be working again, cheers!

**Comment by MetalHeadSeven** [comment]
Is there an update? I don't see anything on CurseForge yet>
