### ISSUE TITLE
Alpha Slider Inverted?

### ISSUE THREAD

**Issue by DaleHuntGB** [Jaslm/ColorPickerPlus#14]
Hi,

This is super minor, but the Alpha slider is seemingly inverted?

In WeakAuras, when selecting 100 Alpha, the bar is transparent and 0 means it is fully opaque.

![image](https://github.com/Jaslm/ColorPickerPlus/assets/95256492/30e29579-0081-4237-8e28-f5ec43b3f928)

You can see this here, if you look at the WeakAura display, the color swatch is transparent, despite 100 Alpha.

**Comment by rml9ty** [comment]
upvote. just noticed the same thing. thought I was going crazy... alpha slider is indeed reverted.

**Comment by Stanzilla** [comment]
Retail or Classic?

**Comment by DaleHuntGB** [comment]
Retail is what I have tested it on.

**Comment by rml9ty** [comment]
Same here, retail.

**Comment by DaleHuntGB** [comment]
This update has corrected it, however, clicking on the colours in the colour palette will automatically set the alpha to zero.

**Comment by Vreden1** [comment]
https://github.com/Jaslm/ColorPickerPlus/issues/16#issuecomment-1905499572
