### ISSUE TITLE
Can't set colors anymore

### ISSUE THREAD

**Issue by Vreden1** [Jaslm/ColorPickerPlus#15]
1x ColorPickerPlus/ColorPickerPlus.lua:1342: attempt to call field 'swatchFunc' (a nil value)
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:1342: in function `HexTextChanged'
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:1081: in function <ColorPickerPlus/ColorPickerPlus.lua:1080>

Locals:
self = <table> {
 CreateClassPalette = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:675
 CreateCheckerboardBG = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:416
 CreateOpacityBar = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1004
 ShowHideAlpha = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:317
 CleanUpColorPickerFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:347
 Initialize_UI = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1215
 UpdateOldColor = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:245
 CreateHelpFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1159
 UpdateOpacityBarThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:287
 CreateTextBoxes = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1031
 UpdateHexText = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1446
 CreateColorGradient = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:806
 Hooked_OnShow = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:334
 UpdateAlphaText = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1481
 UpdateHSVfromColorPickerRGB = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:207
 PLAYER_LOGIN = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1245
 UpdateRGBTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1432
 UpdateChosenColor = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:239
 UpdateColorTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1412
 CreatePalette = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:613
 UpdateHueBarThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:299
 CreateColorSwatches = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:462
 SetRGBfromHSV = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:210
 CreatePaletteSwitcher = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1201
 UpdateHSVTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1418
 GetAlpha = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:218
 CreatePaletteFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1176
 ADDON_LOADED = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:249
 UpdateColorGraphics = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:310
 CreateCopyPasteArea = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:493
 UpdateGradientColorOverlay = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:234
 UpdateGradientThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:268
 HexTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1310
 RGBTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1253
 CreateHueBar = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:906
 AlphaTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1458
 HSVTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1354
}
textBox = ColorPPBoxX {
 0 = <userdata>
 PixelSnapDisabled = true
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Sha

**Comment by Stanzilla** [comment]
Classic or Retail?

**Comment by Vreden1** [comment]
> Classic or Retail?
Retail and facing errors while setting colors even after the today's latest update

1x ColorPickerPlus/ColorPickerPlus.lua:1345: attempt to call field 'swatchFunc' (a nil value)
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:1345: in function `HexTextChanged'
[string "@ColorPickerPlus/ColorPickerPlus.lua"]:1084: in function <ColorPickerPlus/ColorPickerPlus.lua:1083>

Locals:
self = <table> {
 CreateClassPalette = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:676
 CreateCheckerboardBG = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:417
 CreateOpacityBar = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1007
 ShowHideAlpha = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:318
 CleanUpColorPickerFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:348
 Initialize_UI = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1218
 UpdateOldColor = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:246
 CreateHelpFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1162
 UpdateOpacityBarThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:288
 CreateTextBoxes = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1034
 UpdateHexText = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1449
 CreateColorGradient = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:807
 Hooked_OnShow = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:335
 UpdateAlphaText = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1484
 UpdateHSVfromColorPickerRGB = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:207
 PLAYER_LOGIN = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1248
 UpdateRGBTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1435
 UpdateChosenColor = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:240
 UpdateColorTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1415
 CreatePalette = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:614
 UpdateHueBarThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:300
 CreateColorSwatches = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:463
 SetRGBfromHSV = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:210
 CreatePaletteSwitcher = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1204
 UpdateHSVTexts = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1421
 GetAlpha = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:218
 CreatePaletteFrame = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1179
 ADDON_LOADED = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:250
 UpdateColorGraphics = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:311
 CreateCopyPasteArea = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:494
 UpdateGradientColorOverlay = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:235
 UpdateGradientThumb = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:269
 HexTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1313
 RGBTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1256
 CreateHueBar = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:907
 AlphaTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1461
 HSVTextChanged = <function> defined @ColorPickerPlus/ColorPickerPlus.lua:1357
}
textBox = ColorPPBoxX {
 0 = <userdata>
 PixelSnapDisabled = true
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Sha

**Comment by Stanzilla** [comment]
> > Classic or Retail?
> > Retail and facing errors while setting colors even after the today's latest update
> 
> 1x ColorPickerPlus/ColorPickerPlus.lua:1345: attempt to call field 'swatchFunc' (a nil value) [string "@ColorPickerPlus/ColorPickerPlus.lua"]:1345: in function `HexTextChanged' [string "@ColorPickerPlus/ColorPickerPlus.lua"]:1084: in function <ColorPickerPlus/ColorPickerPlus.lua:1083>
> 
> Locals: self =
> 
> {
> CreateClassPalette = defined @ColorPickerPlus/ColorPickerPlus.lua:676
> CreateCheckerboardBG = defined @ColorPickerPlus/ColorPickerPlus.lua:417
> CreateOpacityBar = defined @ColorPickerPlus/ColorPickerPlus.lua:1007
> ShowHideAlpha = defined @ColorPickerPlus/ColorPickerPlus.lua:318
> CleanUpColorPickerFrame = defined @ColorPickerPlus/ColorPickerPlus.lua:348
> Initialize_UI = defined @ColorPickerPlus/ColorPickerPlus.lua:1218
> UpdateOldColor = defined @ColorPickerPlus/ColorPickerPlus.lua:246
> CreateHelpFrame = defined @ColorPickerPlus/ColorPickerPlus.lua:1162
> UpdateOpacityBarThumb = defined @ColorPickerPlus/ColorPickerPlus.lua:288
> CreateTextBoxes = defined @ColorPickerPlus/ColorPickerPlus.lua:1034
> UpdateHexText = defined @ColorPickerPlus/ColorPickerPlus.lua:1449
> CreateColorGradient = defined @ColorPickerPlus/ColorPickerPlus.lua:807
> Hooked_OnShow = defined @ColorPickerPlus/ColorPickerPlus.lua:335
> UpdateAlphaText = defined @ColorPickerPlus/ColorPickerPlus.lua:1484
> UpdateHSVfromColorPickerRGB = defined @ColorPickerPlus/ColorPickerPlus.lua:207
> PLAYER_LOGIN = defined @ColorPickerPlus/ColorPickerPlus.lua:1248
> UpdateRGBTexts = defined @ColorPickerPlus/ColorPickerPlus.lua:1435
> UpdateChosenColor = defined @ColorPickerPlus/ColorPickerPlus.lua:240
> UpdateColorTexts = defined @ColorPickerPlus/ColorPickerPlus.lua:1415
> CreatePalette = defined @ColorPickerPlus/ColorPickerPlus.lua:614
> UpdateHueBarThumb = defined @ColorPickerPlus/ColorPickerPlus.lua:300
> CreateColorSwatches = defined @ColorPickerPlus/ColorPickerPlus.lua:463
> SetRGBfromHSV = defined @ColorPickerPlus/ColorPickerPlus.lua:210
> CreatePaletteSwitcher = defined @ColorPickerPlus/ColorPickerPlus.lua:1204
> UpdateHSVTexts = defined @ColorPickerPlus/ColorPickerPlus.lua:1421
> GetAlpha = defined @ColorPickerPlus/ColorPickerPlus.lua:218
> CreatePaletteFrame = defined @ColorPickerPlus/ColorPickerPlus.lua:1179
> ADDON_LOADED = defined @ColorPickerPlus/ColorPickerPlus.lua:250
> UpdateColorGraphics = defined @ColorPickerPlus/ColorPickerPlus.lua:311
> CreateCopyPasteArea = defined @ColorPickerPlus/ColorPickerPlus.lua:494
> UpdateGradientColorOverlay = defined @ColorPickerPlus/ColorPickerPlus.lua:235
> UpdateGradientThumb = defined @ColorPickerPlus/ColorPickerPlus.lua:269
> HexTextChanged = defined @ColorPickerPlus/ColorPickerPlus.lua:1313
> RGBTextChanged = defined @ColorPickerPlus/ColorPickerPlus.lua:1256
> CreateHueBar = defined @ColorPickerPlus/ColorPickerPlus.lua:907
> AlphaTextChanged = defined @ColorPickerPlus/ColorPickerPlus.lua:1461
> HSVTextChanged = defined @ColorPickerPlus/ColorPickerPlus.lua:1357
> }
> textBox = ColorPPBoxX {
> 0 =
> PixelSnapDisabled = true
> OnBackdropLoaded = defined @SharedXML/Backdrop.lua:152
> Center = Texture {
> }
> GetBackdropColor = defined @SharedXML/Backdrop.lua:390
> SetupTextureCoordinates = defined @SharedXML/Backdrop.lua:214
> OnBackdropSizeChanged = defined @SharedXML/Backdrop.lua:182
> HasBackdropInfo = defined @sha

Can you post the exact steps of what you are doing, I can't really reproduce it here

**Comment by Vreden1** [comment]
> > > Classic or Retail?
> > > Retail and facing errors while setting colors even after the today's latest update
> > 
> > 
> > 1x ColorPickerPlus/ColorPickerPlus.lua:1345: attempt to call field 'swatchFunc' (a nil value) [string "@ColorPickerPlus/ColorPickerPlus.lua"]:1345: in function `HexTextChanged' [string "@ColorPickerPlus/ColorPickerPlus.lua"]:1084: in function <ColorPickerPlus/ColorPickerPlus.lua:1083>
> 
> Can you post the exact steps of what you are doing, I can't really reproduce it here

Today I updated my addons 
logged into the game and tried to check if colorpicker is working correctly by trying to change elvui value color and the error happened and it changed value of other option too beside the one i was trying to change

Addons i have currently enabled:
Buggrabber
Bugsack
Colorpicker
SharedMedia
Leatrix plus
Weakauras
OmniCC
ElvUI
AddonSkins
Details
BigWigs
LittleWigs
Plater

The error occurred on the first thing I tried to change upon logging in and I was afraid to check on other colors because it is also changing the values of the some other colors which I didn't want to change (I am afraid I will mess up my UI)

This is the ss of the option I tested upon:
![WoWScrnShot_012124_182838](https://github.com/Jaslm/ColorPickerPlus/assets/70207642/8c1e21c8-f557-48ea-badb-2b0d22b746a4)
