### ISSUE TITLE
Alpha values reversing

### ISSUE THREAD

**Issue by Vreden1** [Jaslm/ColorPickerPlus#16]
Alpha value is reversed if I type in the exact value in the box labeled 'A' but if I use the slider to adjust the number then correct value is set.
Also the alpha value bar image should be reversed

**Comment by rml9ty** [comment]
to add to that: if you copy/paste a color, the alpha is not taken into account and just defaults to zero.
(also mentioned this in the now closed issue 14, just in case closed issues don't get notifications)

**Comment by Stanzilla** [comment]
Sorry about that, I did not spend a lot of time testing, I just pushed a new version, can you tell me if it's better there? (r59 should be up on CF soon)

**Comment by Vreden1** [comment]
> Sorry about that, I did not spend a lot of time testing, I just pushed a new version, can you tell me if it's better there? (r59 should be up on CF soon)

All the issues mentioned here are solved except the alpha bar image is still inverted (More I move towards the brighter side more my color fades). Is it intended?

**Comment by Vreden1** [comment]
> the black to white vertical bar? I think the intention is that black is 100% alpha and white 0%?

That makes sense. Thank you for the quick resolutions. Please close this thread.

**Comment by Vreden1** [comment]
> the black to white vertical bar? I think the intention is that black is 100% alpha and white 0%?

On a side note I will suggest a couple of changes
1. you can use this checkered background for the vertical alpha bar (I think blizz is using it by default)
2. change it's foreground from alpha gradiant of black to the color that is selected
