### ISSUE TITLE
Separate zips for vanilla/classic/bcc

### ISSUE THREAD

**Issue by austen0** [Jaslm/ColorPickerPlus#2]
Including separate zips for each version in the github releases will make it easier to download/update the mod without Overwolf/Curseforge. Can be automated with github actions and the [BigWigs releaser](https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow).

**Comment by Jaslm** [comment]
Sorry, but I am no longer supporting this software.  Feel free to take it over.

**Comment by timmywil** [comment]
I have forked this repo and made the addon available on [wago](https://addons.wago.io/addons/colorpickerplus) and [my GitHub](https://github.com/timmywil/ColorPickerPlus). I've also enabled [issues](https://github.com/timmywil/ColorPickerPlus/issues) there.
