### ISSUE TITLE
Classic Era Update 1.15.1

### ISSUE THREAD

**Issue by maximus210793** [Jaslm/ColorPickerPlus#21]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.1?
Would be awesome, thanks a lot in advance!

**Comment by Stanzilla** [comment]
Pull Requests welcome but I personally don't want to deal with the mess that Blizzard made there

**Comment by maximus210793** [comment]
Is there a fix for it? Would be so nice to have the addon working again?
Thanks in advance!
